### ISSUE TITLE
Library conflict

### ISSUE THREAD

**Issue by OnlyHigh** [bcgsc/transabyss#13]
Hi, 
Just reporting an issue with Python3,

```
Traceback (most recent call last):
  File "/home/bio/anaconda3/bin/transabyss", line 4, in <module>
    __import__('pkg_resources').run_script('transabyss==1.54', 'transabyss')
  File "/home/bio/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/bio/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/home/bio/anaconda3/lib/python3.6/site-packages/transabyss-1.54-py3.6.egg-info/scripts/transabyss", line 19, in <module>
    from transabyss.adj_utils import has_edges
  File "/home/bio/anaconda3/lib/python3.6/site-packages/transabyss/adj_utils.py", line 7, in <module>
    import igraph
  File "/home/bio/anaconda3/lib/python3.6/site-packages/igraph/__init__.py", line 8, in <module>
    raise DeprecationWarning("To avoid name collision with the igraph project, "
DeprecationWarning: To avoid name collision with the igraph project, this visualization library has been renamed to 'jgraph'. Please upgrade when convenient.
```
Cheers! 
Luis Alfonso.

**Comment by kmnip** [comment]
I think I know what happened... FYI:
https://stackoverflow.com/questions/36200707/error-with-igraph-library-deprecated-library

It looks like a Python package called `igraph` was installed instead of `python-igraph`. So, you need to uninstall `igraph` and then re-install `python-igraph`.

**Comment by OnlyHigh** [comment]
Thanks a lot, but it haven't worked. I'm trying to figure it out how to use transabyss inside a virtual enviroment
